apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quantumrisk-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - host: app.quantumrisk.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quantumrisk-frontend-svc
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: quantumrisk-backend-svc
                port:
                  number: 80
