apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quantumrisk-postgres
spec:
  serviceName: quantumrisk-postgres
  replicas: 1
  selector:
    matchLabels:
      app: quantumrisk-postgres
  template:
    metadata:
      labels:
        app: quantumrisk-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: quantumrisk-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: quantumrisk-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quantumrisk-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: quantumrisk-postgres
spec:
  selector:
    app: quantumrisk-postgres
  ports:
    - port: 5432
      targetPort: 5432
